---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbwebappdeployment
  namespace: efklog
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: sb-web-app
      version: v1
      color: blue
  template:
    metadata:
      labels: 
        app: sb-web-app
        version: v1
        color: blue
    spec:
      containers:
        - name: sbwebappcontainer
          image: ashokit/sb-logger-app
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: sbappscv
  namespace: efklog
spec:
  type: LoadBalancer
  selector:
    app: sb-web-app
    version: v1
    color: blue
  ports:
    - port: 80
      targetPort: 8080
